name: Android CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Test's Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Unit Test Reports
          path: app/build/reports/tests/testDebugUnitTest

      - name: Build with Gradle
        run: ./gradlew build
